import Head from 'next/head';
import dynamic from 'next/dynamic';

const Data = dynamic(() => import('../components/data'), { ssr: false });

export default function DataPage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="w-full h-screen">
          <Data />
        </div>
      </main>
    </div>
  );
}
